services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    YaPro\SymfonyHttpClientExt\:
        resource: '../'
        exclude:
            - '../src/Decorator/'
            - '../src/DependencyInjection/'
            - '../src/SymfonyHttpClientExtBundle.php'
